name: Run Executable Daily

on:
    schedule:
      - cron: '30 22 * * *' # 前日の22時30分 (UTC)、日本時間で午前7時30分
      - cron: '45 15 * * *' # 前日の15時45分 (UTC)、日本時間で午後0時45分
      - cron: '0 20 * * *' # 前日の20時 (UTC)、日本時間で午後5時
      - cron: '0 23 * * *' # 前日の23時 (UTC)、日本時間で午後8時
    workflow_dispatch:

jobs:
  run-executable:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout exec branch
      uses: actions/checkout@v3
      with:
        ref: exec # execブランチを指定

    - name: Set up permissions
      run: chmod +x ./main

    - name: Run executable
      env:
        URL: ${{ secrets.URL }} # 環境変数URLをSecretsから取得
        TOKEN: ${{ secrets.TOKEN }} # 環境変数TOKENをSecretsから取得
      run: ./main
